/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/lootlog/api/auth/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Callback OAuth
         * @description OAuth user authorize
         */
        post: operations["oauthCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lootlog/api/profile/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["myProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lootlog/api/battle-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List of battles
         * @description List of fights with participants, distribution of loots etc.
         */
        get: operations["getAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lootlog/api/battle-loots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List of battle loots
         * @description List of battle loots from fights with special NPCs (HERO, ELITE_II, TITAN)
         */
        get: operations["getAll_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lootlog/api/battle-dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List of battle dates
         * @description List of battle dates from fights with special NPCs (HERO, ELITE_II, TITAN)
         */
        get: operations["getAll_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OAuthCodePayload: {
            code?: string;
        };
        OAuthTokenResponse: {
            token?: string;
        };
        LootlogUserDTO: {
            id?: string;
            login?: string;
            email?: string;
            name?: string;
            avatar?: string;
            baseAssetsPath?: string;
        };
        AssignedItem: {
            /** @description Loot id in loot window. It's just the id in the window for assigning a specific item. */
            lootItemId: string;
            /**
             * Format: int64
             * @description Base id of the item that can be found in the map editor
             */
            baseItemId: number;
            /** @description Item name */
            baseItemName: string;
            /** @description Id of items created in the bag. This is a list because when we get a consumable item, it can connect us with another existing item in the bag and add a second one if there is a maximum number of uses. */
            itemIds: string[];
            /** @description Id of the hero who got the item */
            characterId: string;
            /** @description Character name */
            characterName: string;
        };
        BaseItemDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
            src?: string;
            attributes?: components["schemas"]["ItemAttributes"];
            /** @enum {string} */
            category?: "oneHanded" | "armors" | "twoHanded" | "halfHanded" | "gloves" | "helmets" | "boots" | "rings" | "necklaces" | "shields" | "staffs" | "auxiliary" | "quests" | "consumable" | "neutrals" | "backpacks" | "wands" | "distances" | "arrows" | "talismans" | "upgrades" | "books" | "keys" | "golds";
            /** @enum {string} */
            currency?: "gold" | "unset" | "dragonTear" | "honor";
            /** Format: int32 */
            price?: number;
            /** @enum {string} */
            rarity?: "common" | "unique" | "heroic" | "legendary" | "upgraded" | "artefact";
        };
        CharacterLiteDTO: {
            id: string;
            name: string;
            src: string;
            /** Format: int32 */
            lvl?: number;
            /** @enum {string} */
            profession: "p" | "w" | "t" | "h" | "m" | "b";
        };
        ItemAttributes: {
            attributes?: {
                [key: string]: Record<string, never>;
            };
            /** Format: int32 */
            maxQuantity?: number;
        };
        LootItemDTO: {
            id: string;
            item: components["schemas"]["BaseItemDTO"];
            /** Format: int64 */
            npcId: number;
            wantCharacterIds: string[];
            dontCharacterIds: string[];
            needCharacterIds: string[];
        };
        LootlogBattleRecordDTO: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            characters: components["schemas"]["LootlogCharacterLiteDTO"][];
            npcs: components["schemas"]["NpcDTO"][];
            attackerId: string;
            attackerType: string;
            lootsAllocation?: components["schemas"]["LootsAllocationDTO"];
        };
        LootlogCharacterLiteDTO: {
            id: string;
            name: string;
            src: string;
            /** Format: int32 */
            lvl?: number;
            /** @enum {string} */
            profession: "p" | "w" | "t" | "h" | "m" | "b";
        };
        LootsAllocationDTO: {
            /** @description List of characters who got the loot window */
            characters: components["schemas"]["CharacterLiteDTO"][];
            /** @description List of items in the loot window */
            items: components["schemas"]["LootItemDTO"][];
            /** @description Id of characters who confirmed the loot window before the time expired */
            confirmedCharacterIds: string[];
            /** @description Allocation of loot - who got what item */
            assignedItems: components["schemas"]["AssignedItem"][];
        };
        NpcDTO: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            mapId: number;
            name: string;
            src: string;
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
            /** Format: int32 */
            lvl: number;
            /** @enum {string} */
            rank: "NORMAL" | "ELITE" | "ELITE_II" | "ELITE_III" | "HERO" | "TITAN";
            /** @enum {string} */
            profession: "p" | "w" | "t" | "h" | "m" | "b";
            inGroup: boolean;
            /** Format: int32 */
            minRespawnTime: number;
            /** Format: int32 */
            maxRespawnTime: number;
        };
        PageLootlogBattleRecordDTO: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["LootlogBattleRecordDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        SortObject: {
            empty?: boolean;
            unsorted?: boolean;
            sorted?: boolean;
        };
        ItemDTO: {
            id?: string;
            name?: string;
            src?: string;
            /** Format: int32 */
            position?: number;
            /** @enum {string} */
            location?: "BAG" | "EQUIPMENT" | "MAP" | "BAGS_AREA" | "CITY_MAIL" | "DEPOSIT";
            /** Format: int64 */
            baseItemId?: number;
            attributes?: components["schemas"]["ItemAttributes"];
            /** @enum {string} */
            category?: "oneHanded" | "armors" | "twoHanded" | "halfHanded" | "gloves" | "helmets" | "boots" | "rings" | "necklaces" | "shields" | "staffs" | "auxiliary" | "quests" | "consumable" | "neutrals" | "backpacks" | "wands" | "distances" | "arrows" | "talismans" | "upgrades" | "books" | "keys" | "golds";
            /** @enum {string} */
            currency?: "gold" | "unset" | "dragonTear" | "honor";
            /** Format: int32 */
            price?: number;
            /** @enum {string} */
            rarity?: "common" | "unique" | "heroic" | "legendary" | "upgraded" | "artefact";
            /** Format: int32 */
            bagNumber?: number;
        };
        LootlogBattleLootDTO: {
            id: string;
            battleId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            characters: components["schemas"]["CharacterLiteDTO"][];
            npcs: components["schemas"]["NpcDTO"][];
            /** @description IDs of items that were in the loot window */
            itemIds: string[];
            /** @description Allocation of loot - who got what item */
            assignedItems: components["schemas"]["AssignedItem"][];
            /** @description ID of characters who confirmed the loot window before the time expired */
            confirmedCharacterIds: string[];
            /** @description Items that were in the loot window */
            items: components["schemas"]["ItemDTO"][];
        };
        PageLootlogBattleLootDTO: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["LootlogBattleLootDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        LootlogBattleDateDTO: {
            id: string;
            battleId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            characters: components["schemas"]["CharacterLiteDTO"][];
            npcs: components["schemas"]["NpcDTO"][];
        };
        PageLootlogBattleDateDTO: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["LootlogBattleDateDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    oauthCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthCodePayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OAuthTokenResponse"];
                };
            };
        };
    };
    myProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LootlogUserDTO"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query?: {
                npcName?: string;
                characterName?: string;
                minNpcLvl?: number;
                maxNpcLvl?: number;
                npcRank?: "NORMAL" | "ELITE" | "ELITE_II" | "ELITE_III" | "HERO" | "TITAN";
                minCharacterLvl?: number;
                maxCharacterLvl?: number;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageLootlogBattleRecordDTO"];
                };
            };
        };
    };
    getAll_1: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageLootlogBattleLootDTO"];
                };
            };
        };
    };
    getAll_2: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageLootlogBattleDateDTO"];
                };
            };
        };
    };
}
